"""init

Revision ID: c9c4b160d435
Revises:
Create Date: 2026-06-10 20:23:40.817496
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c9c4b160d435"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("mail", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mail"),
    )
    op.create_table(
        "objetivos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("imagen", sa.String(length=500), nullable=True),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "descripciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feria", sa.String(length=200), nullable=False),
        sa.Column("local", sa.String(length=200), nullable=False),
        sa.Column("moneda", sa.String(length=10), nullable=False),
        sa.Column("precio", sa.Float(), nullable=False),
        sa.Column("objetivo_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["objetivo_id"], ["objetivos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("descripciones")
    op.drop_table("objetivos")
    op.drop_table("usuarios")
    # ### end Alembic commands ###
